# Use root/example as user/password credentials
version: "3.1"

services:
  vegan-studio-backend:
    build: .
    container_name: vegan-studio-backend
    restart: always
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    ports:
      - 888:8080
    depends_on:
      mysql-pdex:
    volumes:
      - .:/usr/src/app/
      - node_modules:/usr/src/app/node_modules
  mysql:
    image: mysql:5.7.19
    container_name: mysql-veganstudio
    restart: unless-stopped
    ports:
      - 49159:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vegan_studio
      MYSQL_USER: root
    volumes:
      - vol-mysql:/var/lib/mysql
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
volumes:
  node_modules:
  vol-mysql:
